# Generated by Django 5.2 on 2025-04-24 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(default='default@example.com', max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('pfp', models.ImageField(upload_to='profile_pics/')),
                ('type', models.CharField(choices=[('organizer', 'Organizer'), ('attendee', 'Attendee')], default='organizer', max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='AttendeeUser',
        ),
        migrations.DeleteModel(
            name='OrganizerUser',
        ),
    ]
