# Generated by Django 5.2 on 2025-04-24 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_user_delete_attendeeuser_delete_organizeruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='papa', max_length=255),
        ),
    ]
