# Generated by Django 5.1.5 on 2025-04-09 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createEvents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.CharField(max_length=255),
        ),
    ]
