# Generated by Django 5.2 on 2025-04-27 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createEvents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Male'), ('other', 'Other'), ('do not wish to specify', 'Do not wish to specify')], default='male', max_length=100),
        ),
    ]
