# Generated by Django 5.2 on 2025-04-27 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createEvents', '0002_rsvp_age_rsvp_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Male'), ('other', 'Other'), ('do not wish to specify', 'Do not wish to specify')], default='pick option', max_length=100),
        ),
    ]
