# Generated by Django 5.2 on 2025-04-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createEvents', '0004_alter_rsvp_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='org_email',
            field=models.EmailField(default='a@a.com', max_length=255),
        ),
    ]
